# bind C-M send-prefix

# Mouse
set -g mouse on

set-option -g allow-rename off


# Bindings

# Alt+Z to split vertical (side-by-side)
bind -n M-z split-window -h

# Alt+X to split horizontal (top-to-bottom)
bind -n M-x split-window -v

# Alt+C to remove (kill) the current pane
bind -n M-c kill-pane

# Move between panes using Alt+WASD
bind -n M-w select-pane -U
bind -n M-a select-pane -L
bind -n M-s select-pane -D
bind -n M-d select-pane -R

# Alt+N to create a new window
bind -n M-n new-window

# Alt+M to rename the current window
bind -n M-m command-prompt -I "#W" "rename-window '%%'"

# Alt+< and Alt+> to cycle through windows
# (Note: These often require the Shift key: Alt+Shift+, and Alt+Shift+.)
bind -n M-e previous-window
bind -n M-q next-window

# Alt+/ to close active window
bind -n M-/ kill-window
